appid: "331470"
publishedfileid: "1746278653"         
visibility: "0"               
title: "Один украденный день"
changenote: "Технические доработки, оптимизация кода."
previewfile: "deploy/avatar.png"
project_name: "osd"
exclusions:
  - ".git"
  - ".github"
  - ".gitattributes"
  - ".gitignore"
  - ".vscode"
  - "scripts"
  - "steamcmd"
  - "build"
  - "README.md"
  - "deploy"
  - "exclusions.yml"
  - "markers.yml"